@hostname = http://localhost:3000

# 获取推荐歌单
GET {{hostname}}/personalized HTTP/1.1

# 获取推荐新音乐
GET {{hostname}}/personalized/newsong HTTP/1.1

# 获取网友精选碟歌单
GET {{hostname}}/top/playlist HTTP/1.1

# 获取推荐中的精品歌单
GET {{hostname}}/top/playlist/highquality HTTP/1.1

# 获取获取新歌速递
GET {{hostname}}/top/song HTTP/1.1

# 获取歌单详情
GET {{hostname}}/playlist/detail?id=3136952023 HTTP/1.1

# 获取歌曲详情
GET {{hostname}}/song/detail?ids=1427471795,28978321 HTTP/1.1
